#ifndef WN_FP_MB4_CRYPTO_P256_H
#define WN_FP_MB4_CRYPTO_P256_H
#include "mbedtls4_crypto_config.h"
#undef PSA_WANT_ALG_RSA_PKCS1V15_SIGN
#undef PSA_WANT_ALG_RSA_PSS
#undef PSA_WANT_KEY_TYPE_RSA_PUBLIC_KEY
#undef PSA_WANT_KEY_TYPE_RSA_KEY_PAIR
#undef PSA_WANT_ALG_SHA_384
#undef PSA_WANT_ALG_SHA_512
#undef PSA_WANT_ECC_TWISTED_EDWARDS_255
#undef PSA_WANT_ALG_ED25519PH
#undef PSA_WANT_ALG_PURE_EDDSA
#endif
